proc extractBELs {lstObjects name} {
    set lst [lsearch -all -inline $lstObjects "*\([string tolower $name]\)*"]
    lappend lst {*}[lsearch -all -inline $lstObjects "*\([string toupper $name]\)*"]

    if { [llength $lst] > 0 } {
        set msg "${name}s      : [llength $lst]"
        echo $msg

        set fo [open "sim/design_info.log" a]
        puts $fo $msg
        foreach item $lst { puts $fo "$item" }
        puts $fo "\n"
        close $fo

        return $lst
    } else {
        return ""
    }
}

echo "================ DESIGN REPORT ================"

set fo [open "sim/design_info.log" w]
close $fo

set lstObjects [find instance -r *]

set ALL_BELs "
{AND2B1L} {AUTOBUF} {BIBUF} {BSCANE2} {BUF} {BUFCE_LEAF} {BUFCE_ROW} {BUFG_GT_SYNC} {BUFG_GT} {BUFG_PS} {BUFG} {BUFGCE_DIV} {BUFGCE} {BUFGCTRL} {BUFGP} {BUFH}
{BUFHCE} {BUFIO} {BUFMR} {BUFMRCE} {BUFR} {CAPTUREE2} {CARRY4} {CARRY8} {CFGLUT5} {DCIRESET} {DCM_ADV} {DCM_SP} {DIFFINBUF} {DNA_PORT} {DNA_PORTE2} {DPHY_DIFFINBUF}
{DSP_A_B_DATA} {DSP_ALU} {DSP_C_DATA} {DSP_M_DATA} {DSP_MULTIPLIER} {DSP_OUTPUT} {DSP_PREADD_DATA} {DSP_PREADD} {DSP48E1} {DSP48E2} {EFUSE_USR} {FDCE} {FDPE} {FDRE}
{FDSE} {FIFO18E1} {FIFO18E2} {FIFO36E1} {FIFO36E2} {FRAME_ECCE2} {FRAME_ECCE3} {FRAME_ECCE4} {GLBL_VHD} {GND} {HARD_SYNC} {HPIO_VREF} {IBUF_ANALOG} {IBUF_IBUFDISABLE}
{IBUF_INTERMDISABLE} {IBUF} {IBUFCTRL} {IBUFDS_DIFF_OUT_IBUFDISABLE} {IBUFDS_DIFF_OUT_INTERMDISABLE} {IBUFDS_DIFF_OUT} {IBUFDS_DPHY} {IBUFDS_GTE2} {IBUFDS_GTE3}
{IBUFDS_GTE4} {IBUFDS_IBUFDISABLE_INT} {IBUFDS_IBUFDISABLE} {IBUFDS_INTERMDISABLE_INT} {IBUFDS_INTERMDISABLE} {IBUFDS} {IBUFDSE3} {IBUFE3} {ICAPE2} {ICAPE3} {IDDR_2CLK}
{IDDR} {IDDRE1} {IDELAYCTRL} {IDELAYE2_FINEDELAY} {IDELAYE2} {IDELAYE3} {INBUF} {INV} {IOBUF_ANALOG} {IOBUF_DCIEN} {IOBUF_INTERMDISABLE} {IOBUF} {IOBUFDS_DCIEN}
{IOBUFDS_DIFF_OUT_DCIEN} {IOBUFDS_DIFF_OUT_INTERMDISABLE} {IOBUFDS_DIFF_OUT} {IOBUFDS_INTERMDISABLE} {IOBUFDS} {IOBUFDSE3} {IOBUFE3} {ISERDES_NODELAY} {ISERDES}
{ISERDESE1} {JTAG_SIME2} {KEEPER} {LDCE} {LDPE} {LUT1} {LUT2} {LUT3} {LUT4} {LUT5} {LUT6_2} {LUT6} {MASTER_JTAG} {MMCME2_ADV} {MMCME2_BASE} {MMCME3_ADV} {MMCME3_BASE}
{MMCME4_ADV} {MMCME4_BASE} {MUXCY} {MUXF7} {MUXF8} {MUXF9} {OBUF} {OBUFDS_DPHY} {OBUFDS_GTE3_ADV} {OBUFDS_GTE3} {OBUFDS_GTE4_ADV} {OBUFDS_GTE4} {OBUFDS} {OBUFT_DCIEN}
{OBUFT} {OBUFTDS_DCIEN} {OBUFTDS} {ODDR} {ODDRE1} {ODELAYE2_FINEDELAY} {ODELAYE2} {ODELAYE3} {OR2L} {OSERDES} {OSERDESE1} {PHASER_REF} {PLLE2_ADV} {PLLE2_BASE}
{PLLE3_ADV} {PLLE3_BASE} {PLLE4_ADV} {PLLE4_BASE} {PS7} {PULLDOWN} {PULLUP} {RAM32M} {RAM32M16} {RAM32X1D} {RAM32X1S} {RAM32X16DR8} {RAM64M} {RAM64M8} {RAM64X1D}
{RAM64X1S} {RAM64X8SW} {RAM128X1D} {RAM128X1S} {RAM256X1D} {RAM256X1S} {RAM512X1S} {RAMB18E1} {RAMB18E2} {RAMB36E1} {RAMB36E2} {RAMD32} {RAMD64E} {RAMS32} {RAMS64E}
{RAMS64E1} {RIU_OR} {SIM_CONFIGE2} {SIM_CONFIGE3} {SRL16E} {SRLC16E} {SRLC32E} {STARTUPE2} {STARTUPE3} {SYSMONE1} {SYSMONE4} {URAM288_BASE} {URAM288} {USR_ACCESSE2}
{VCC} {VCU} {XADC} {XORCY} {ZHOLD_DELAY}
"

set belsCount 0
foreach bel $ALL_BELs {
    set belsCount [expr $belsCount + [llength [extractBELs $lstObjects "$bel"]]]
}
echo "-----------------------------------------------"
echo "Total BELs      : $belsCount"

echo "==============================================="

# exit
